* 绪论-马克思主义是关于无产阶级和人类解放的科学
** 1. 马克思主义的产生和发展
*** 1. 马克思主义科学体系内容
*** 2. 德国古典哲学、英国古典政治经济学、英法空想社会主义学说、自然科学的三大发现
*** 3. 马克思主义直接理论来源
马克思主义是对人类文明成果的继承和创新，德国古典哲学、英国古典政治经济学、英法空想社会主义学说，是它的直接理论来源，马克思主义的产生还与当时自然科学的巨大成就密切相关。
*** 4. 为什么马克思主义是时代的产物
马克思主义是时代的产物，它产生于资本主义社会化大生产已经成为主导趋势，资本主义社会内部各种社会矛盾充分显露，无产阶级以独立的政治力量登上历史舞台争取自身和人类解放的历史时代。
*** 5. 马克思主义在实践中不断发展
首先，马克思主义不是脱离实际的抽象的思辨体系，它永远面对现实世界，面对实际生活，关注和研究时代提出的最迫切的问题，总结新的实践经验，提出新的理论观点。其次，马克思主义不是宗派主义体系，它能正确地对待各种非马克思主义，甚至反马克思主义的学说，对它们进行批判地研究，剔除其中错误的观点，吸收其积极合理的内容。再次，马克思主义不是固步自封的体系，它具有自我批判的意识，它能根据时代的变化、实践的发展和科学的进步，发现自身的历史局限性和不完善的地方，把自身提高到与时代和实践的需要更加适应的水平。
** 2. 马克思主义科学性与革命性的统一
*** 1. 马克思主义科学内涵
马克思主义是由马克思、恩格斯创立的没，为他们后继者所发展的，以反对资本主义、建设社会主义和共产主义为目标的科学的理论体系，简要地说，它是关于工人阶级和人类解放的科学。以实践为基础的科学性和革命性的统一，是马克思主义理论的根本特征。其革命性主要表现为它按照世界本来的面目认识世界，揭示了自然界和人类社会的发展规律。它的科学性和革命性在实际的基础上达到统一。
*** 2. 马克思主义理论特征
以实践为基础的科学性和革命性的统一。
*** 3. 理想
理想是人类奋斗的目标。理想的内容划分有：生活理想、职业理想、道德理想、社会理想等。
1. 生活理想是人们对未来的衣、食、住、行、爱情、婚姻、家庭等具体目标的向往和追求。
2. 职业理想是人们对未来工作类别的选择，以及对从事某项工作后达到何种绩效的向往和追求。
3. 道德理想是人们对做人标准和道德境界的向往和追求。
4. 社会理想是人们对未来社会制度、社会风貌的期望和追求。
四种理想互相联系、互相渗透、互相制约、互相影响。其中社会理想是最根本的，是全部理想的核心，它贯穿于生活理想、职业理想、道德理想之中，决定和制约着他们的发展和实现程度，而生活理想、职业理想、道德理想又从不同的侧面直接或间接的体现社会理想。
*** 4. 马克思主义社会理想
推翻资本主义、实现社会主义和共产主义
*** 5. 马克思主义革命性
表现在它具有鲜明的政治立场上。马克思主义是工人阶级的意识形态，它以科学的理论形式反映了工人阶级和广大人民群众的利益、愿望和要求。它丝毫不避讳和隐瞒自己的阶级本质，不以“超阶级”的幌子标榜自己是“全人类”利益的代表，而是公然申明自己的阶级性，申明自己是为工人阶级服务的。它坚决批判一切剥削阶级的理论观点，自觉捍卫无产阶级和广大人民群众的利益，以彻底推翻一切剥削制度、消灭社会不平等的现象、争取工人阶级和全人类的彻底解放为己任。
*** 6. 马克思主义科学性
首先它不带任何偏见，清除一切狭隘性和片面性的弊端，力求按照世界的本来面目去如实地认识世界，揭示了自然界和人类社会发展的客观规律，并根据对客观规律的认识去能动地改造世界。其次，马克思主义的科学性还在于它的深刻性。
马克思主义之所以具有科学性，不仅在于它揭示了自然界和人类社会发展的客观规律，而且还在于它经受了实践的检验并随着实践的发展而不断发展。
*** 7. 马克思主义是行动的指南
马克思主义不是教条，而是行动的指南。它提供研究的方法，而不提供对一切问题的现成答案。必须把马克思主义的一般原理与本国的具体实际相结合。
*** 8. 马克思主义科学性和革命性在实践基础上的统一
马克思主义的科学性和革命性都是以实践为基础的。实践的观点是马克思主义的基本观点，是马克思主义的出发点和归宿。马克思主义来源于实践，是实践经验的概括和总结，又反过来指导工人阶级和广大人民群众改造世界的实践活动，为实践服务，并在实践中得到检验和发展。离开了无产阶级和广大人民群众的实践活动，马克思主义就成了无源之水、无本之木，就丧失了认识世界和改造世界的功能，就失去了存在的意义。
*** 9. 习近平新时代中国特色社会主义理想
*** 10. 马克思主义的理论品质
与时俱进是马克思主义的理论品质。与时俱进就是党的全部理论和工作要体现时代性，把握规律性，富于创造性。马克思主义创始人和继承者都是与时俱进的典范。
*** 11. 马克思主义最高理想与全国各族人民的共同理想关系
共同理想是实现最高理想的必经阶段和必要基础。最高理想和共同理想都是以马克思主义的科学理论为指南的，它们的实现都离不开工人阶级政党的正确领导，就是说它们属于同一思想体系和同一种政治立场。但是，共同理想是在共产主义理想大目标指导下社会发展阶段中的奋斗目标。实现共产主义理想是一个漫长的过程，需要经过许多不尽相同的发展阶段，每一个阶段都会有特定的奋斗目标，这些特定的奋斗目标又都是为共产主义这个总目标服务的。
最高理想的实现，离不开共同理想的实现所创造的物质、精神条件。没有各个阶段中特定目标和具体任务的完成，实现共产主义最高理想就只能是一句空话。
最高理想与共同理想既相区别又相联系，二者是辩证统一的关系。
** 3. 学习、运用和发展马克思主义
*** 1. 学习马克思主义目的
1. 树立正确的人生观、价值观、世界观。
2. 掌握认识世界和改造世界的伟大工具。
3. 全面提高人的素质。
4. 指导中国特色社会主义伟大实践。
*** 2. 学习马克思主义根本方法
1. 理论联系实际是学习马克思主义的根本方法。
2. 就是要把马克思主义的基本原理作为指导，去观察分析社会实际。
3. 在实际工作中必须反对经验主义和教条主义两种倾向。
